# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b651f4c52f57dbceab62251100c902b8ea96a68b43f4cacbb1feda168edc2aabeed4e1d7835a1e5ffa73ae71778f02a3e618f15eabca80b5b33e4d1e726e0a4

test:
  secret_key_base: d7928d49f4fe73fa72fe0468314bf7cb0e1751e769ff63546fe9ec0dc65ed9ae06537282bb360fd65512e02d70485240b7be069e62947610b68b2d038c1e9a31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>